http:
  middlewares:
    standard:
      chain:
        middlewares:
          - retry
          - content-type
          - security
          - inflightreq
          - traefik-real-ip
          - rate-limit-1m
          - compress
