http:
  middlewares:
    rate-limit-1m:
      plugin:
        traefik-rate-limit:
          rateLimit:
            rate: 100
            burst: 100
            period: 60s
          ipResolver:
            header: X-Real-IP
            useSrcIP: false
          whitelistedIPNets: [ ]
          whitelistLocalIPs: false
          redis:
            host: redis
            port: 6379
          logLevel: debug
