name: Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - './cmd/**'
      - './internal/**'
      - 'VERSION'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: stable

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          install-only: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          chmod +x .github/scripts/install_build_deps.sh
          bash .github/scripts/install_build_deps.sh

      - name: Make build
        run: |
          make build/docker

      - name: Set up params
        id: setup_builder
        run: |
          vers=$(tr -d '[:space:]' <VERSION)
          echo "version=$vers" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: |
            docker.io/${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern={{version}}-${{github.run_number}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern={{major}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern=v{{version}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern=v{{version}}-${{github.run_number}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ steps.setup_builder.outputs.version }}
            type=semver,pattern=v{{major}},value=${{ steps.setup_builder.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          logout: true

      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
