name: PR Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - './cmd/**'
      - './internal/**'

permissions:
  contents: write

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5.4.0
        with:
          go-version: stable

      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          install-only: true

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make
          chmod +x .github/scripts/install_build_deps.sh
          bash .github/scripts/install_build_deps.sh

      - name: Build
        run: |
          make tidy
          make build/release
          git diff --exit-code
